### ISSUE TITLE
Video alignment shortcuts

### ISSUE THREAD

**Issue by skyvaheri** [tamius-han/ultrawidify#100]
Hey, I'm sorry if you got a similar request already but I never used GitHub before and I'm a bit struggling to get along. But all I wanted to is to do a feature request.
Is it possible to add video alignment shortcuts? For example something like strg + (arrow-) left or right?
Thanks a lot 
David

I'm sorry but I am pretty sure I'm in the wrong category but I wasnt able to find the category for new feature request or something similar.

**Comment by tamius-han** [comment]
Oi, sorry for long response. Had a bit of a hard week at work at the time and then, in true Benioff & Weiss fashion, kinda forgot (tm).

Yes, you can add custom shortcuts in extension settings.

Yes, the UI is mildly bugged, but it works well enough-ish.
