### ISSUE TITLE
Video misaligned on hbonow

### ISSUE THREAD

**Issue by misterclean111** [tamius-han/ultrawidify#103]
On hbonow it seems like the video won't stretch into the left part of the screen

**Screenshots**
![hbo1](https://user-images.githubusercontent.com/65588068/82292634-18310f80-9960-11ea-85ae-321b149e8736.jpg)
![hbo2](https://user-images.githubusercontent.com/65588068/82292649-1bc49680-9960-11ea-9d7b-6475025a6af4.jpg)

**Browser and OS**
 * Browser/browser version: Firefox and chrome
 * Operating system:Windows 10
 * Ultrawidify version:4.4.8

**Additional info**
This is an 18:9 video not 21:9 dont know if that makes a difference

**Comment by tamius-han** [comment]
> This is an 18:9 video not 21:9 dont know if that makes a difference

That shouldn't make a difference.

Unfortunately though, I don't have access to HBO now, and the video player in HBO GO appears to be different enough from the one in HBO Now that the issue doesn't happen there (even though both sites are by the same company ~~unless they outsourced~~). 

To start things off, I'll need you to provide me with logs.

How to provide logs: https://github.com/tamius-han/ultrawidify/wiki/How-to-provide-logs

Here's the thing that you need to paste into the magic box:
```
{
  "allowLogging": true,
  "timeout": 15,
    "consoleOptions": {
    },
    "fileOptions": {
    "enabled": true,
    "debug": true,
    "init": true,
    "settings": true,
    "keyboard": true,
    "mousemove": true,
    "actionHandler": true,
    "playerDetect": true,
    "resizer": true,
    "scaler": true,
    "stretcher": true,
    "videoRescan": true,
    "playerRescan": true
  },
  "allowBlacklistedOrigins": {
    "periodicPlayerCheck": true,
    "periodicVideoStyleChangeCheck": true
  }
}
```

You have 15 seconds from the moment the page refreshes to reproduce the issue. Logging should automatically conclude after 15 seconds.

**Comment by misterclean111** [comment]
Heres the log, I actually figured out how to drag the video into the
correct place so I guess this isnt really a priority but thanks for looking
into it :)
