### ISSUE TITLE
Stopped working on youtube a few days ago

### ISSUE THREAD

**Issue by Sabrehawk** [tamius-han/ultrawidify#107]
A few days ago the videos on youtube will simply get aligned to the left side , they wont be stretched or anything no matter what i try to do in the context menu or the options menu, removed the plugin, installed it again, same behaviour....

Im out of clues

**Comment by tamius-han** [comment]
Does that still happen?

Bbecause I'm unable to reproduce this issue.

**Comment by sihien87** [comment]
Everytime i restart my computer, reopen firefox yltrawidify stop working, i have to switch the addon on and of few times till it work

**Comment by tamius-han** [comment]
Whoops, I dropped a ball on this one.

I'm gonna need some logs for this one. If you can provide them, that'd be great.

**Opening logger:**
Open popup, click "report a problem" -> show logger (down at the bottom).

Then click 'paste config' button.
![image](https://user-images.githubusercontent.com/12505802/96798530-5d6ed700-1401-11eb-8914-1153818142d6.png)

Paste this into the box:
```
{
  "allowLogging": true,
  "timeout": 3,
    "consoleOptions": {
    "enabled": true,
    "debug": true,
    "init": true,
    "settings": true,
    "keyboard": true,
    "mousemove": true,
    "actionHandler": true,
    "comms": true,
    "playerDetect": true,
    "resizer": true,
    "scaler": true,
    "stretcher": true,
    "zoom": true,
    "videoRescan": true,
    "playerRescan": true,
    "arDetect": true,
    "arDetect_verbose": true
  },
  "allowBlacklistedOrigins": {
    "periodicPlayerCheck": true,
    "periodicVideoStyleChangeCheck": true,
    "handleMouseMove": true
  }
}
```
Click start logging. Close browser immediately. Restart your computer. Open a youtube video. Press F12.


You should see something that resembles this (if need be, switch to 'Console' tab first):
![image](https://user-images.githubusercontent.com/12505802/96798749-d2421100-1401-11eb-8778-fef3cf0215a4.png)

Right click anywhere. In the popup, select "export all visible messages to -> file". Save the file and upload it here (logger is mildly broken at the moment, so you'll have to do it this way).  
![image](https://user-images.githubusercontent.com/12505802/96798891-2220d800-1402-11eb-9714-3a69f531d204.png)
