### ISSUE TITLE
Is webextension-polyfill an option here?

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#114]
I see several BrowserDetect check from the code, mainly to use `chrome` instead of `browser`. There is a polyfill to do this more cleanly, so probably a good choice: https://github.com/mozilla/webextension-polyfill

**Comment by tamius-han** [comment]
It is an option, but — fun story.

Lots of 'BrowserDetect' code has been written back when extension was either still simple enough it didn't need three billion `node_modules`, or getting quite complex but I really didn't want to take an afternoon to migrate things to something that would make sense.

Which lasted until I figured out my popup badly needs Vue (and there was probably a time when webextension-polyfill was actually in my package.json, too). But the BrowserDetect checks were already written, and I really didn't want to spend an afternoon throwing them out and testing whether Chrome version still works — not to mention hunting down BrowserDetect stuff sounds rather boring when put next to the other shiny projects I have in mind. Thus, the cycle continues.

So: It's an option, but given how I almost never ever touch that part of code, it's probably not gonna happen for a while.

**Comment by saschanaz** [comment]
Makes sense, "Fix it only when it's broken". But then, if I ever write a PR that uses the polyfill (probably for some real fix rather than just refactoring), do you think you will accept it?

**Comment by tamius-han** [comment]
Yeah, sure (if it doesn't break anything).

**Comment by tamius-han** [comment]
So here's a fun fact that I just discovered.

... webextension-polyfill doesn't work inside vue components for some reason. Learned the hard way when tried to have `browser.runtime.getURL('/res/icons/bootstrap-icons.svg')` in a vue component (that runs in content script).

**Comment by tamius-han** [comment]
Status update.

Migrating everything to webextension-polyfill might be a necessity when moving the extension to typescript, because typescript absolutely doesn't play ball with your regular `chrome` and `window`.
