### ISSUE TITLE
Video unexpectedly aligns to right on Crunchyroll

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#115]
**Describe the bug**

It aligns to right even when I click the Video alignment: Center button 

**To Reproduce**

I went Crunchyroll and watch BURN THE WITCH https://www.crunchyroll.com/burn-the-witch/episode-2-ghillie-suit-she-makes-me-special-797792

**Expected behavior**

It should be centered but the buttons didn't work

**Screenshots**

(Ignore the right letterbox, it's visually nonexistent and is only there to match the width with my second screen)

![image](https://user-images.githubusercontent.com/3396686/96954862-9b98f300-14f4-11eb-8f95-8b00c029d506.png)

**Browser and OS**
 * Browser/browser version: Firefox 82 and 84
 * Operating system: Windows 10 19042
 * Ultrawidify version: 4.4.10

**Additional info**

This didn't happen a few days ago so I guess this is a recent regression.

**Comment by saschanaz** [comment]
In 21:9 scene it becomes this:

![image](https://user-images.githubusercontent.com/3396686/96955994-46aaac00-14f7-11eb-9948-923c2e2f73f8.png)

**Comment by tamius-han** [comment]
Yes, that's a recent regression. Apparently CSS rules that are there to make sure shit on Hulu and Twitch doesn't get misaligned did end up having some unforeseen side effects.

Also Crunchyroll's video player is a lil bit cancer so:

0. Play a video for a few seconds.
1. Open extension popup
2. Click Advanced Settings.
3. Wait a bit until you get a few URLs under the 'Advanced settings' bit. Click static.crunchyroll.com:
![slika](https://user-images.githubusercontent.com/12505802/97096523-0d487c80-166e-11eb-83bc-f0c1f84bb38f.png)
(Note that URLs may not immediately appear. They might also disappear immediately after clicking static.crunchyroll.com)
4. Paste this into the _second_ "Additional CSS" box (down at the bottom): `align-self: start !important`
5. press enter, click outside the box (but still within the popup), close the popup, refresh the page with F5.

**Comment by saschanaz** [comment]
Step 4 and 5 are tricky, somehow I can't make it. Paste+press enter+clicking anything inside popup+closing popup by clicking outside+F5 still does nothing, and whenever I retry step 4 the box is always empty. 🤷‍♀️

**Comment by tamius-han** [comment]
Oh well, the update should be live soon enough.
