### ISSUE TITLE
"Quick settings" dialogue fails when the extension icon is in pull-down "More tools..." menu list

### ISSUE THREAD

**Issue by DRSAgile** [tamius-han/ultrawidify#119]
Hi,

I use the most of extensions when they are moved from the browser bar to the hidden pull-down "More tools..." menu list, accessible via "»" (French quote sign) button.

However, this specific extension renders its "Quick settings" dialogue in a way which makes it is impossible to use since when invoked from that pull-down menu the accessible space to render is only as big as the menu itself, so everything is cut off. 

It would have been manageable if the extension would at least allow scrolling bars so it would be possible to move right and select a necessary aspect ratio.

Thanks in advance.

**Comment by tamius-han** [comment]
Yay, finally got something sexy:

![image](https://user-images.githubusercontent.com/12505802/101076250-65df3380-35a3-11eb-91ab-7f3ec2420bb9.png)

![image](https://user-images.githubusercontent.com/12505802/101076271-6ed00500-35a3-11eb-98e7-59d992fa3897.png)

I hope I manage to get this out by the end of the weekend.

**Comment by DRSAgile** [comment]
Thanks, it works now.
