### ISSUE TITLE
21:9 not working for Hulu in Microsoft Edge

### ISSUE THREAD

**Issue by rmill3r** [tamius-han/ultrawidify#120]
**Describe the bug**
All videos in Hulu on Microsoft Edge are not aligned. They seem to be aligned to as far to the right as possible. Therefore, if I enable 21:9 in cropping mode, the image is off-centered. 

**To Reproduce**
N/A

**Expected behavior**
The videos should be centered and should fill the width of the screen if I enable the 21:9 cropping mode on my 21:9 monitor.

**Screenshots**
I've attached screenshots from Fargo. The first one is when it is set to 16:9 and the second is when it is set to 21:9. 

![Hulu - Fargo - Ultrawidify - 16-9](https://user-images.githubusercontent.com/72991427/99345410-3a98dc80-2860-11eb-9c77-30352c3ea62a.jpg)

![Hulu - Fargo - Ultrawidify - 21-9](https://user-images.githubusercontent.com/72991427/99345439-50a69d00-2860-11eb-9d21-7a65d1cda4a9.jpg)

**Browser and OS**
 * Browser/browser version: Microsoft Edge Version 86.0.622.69
 * Operating system: Windows 10
 * Ultrawidify version: 4.4.9.2

**Additional info**
I asked about this issue previously using Chrome, and I was told that a fix was in the works and in the meantime, I was given this code to put under "Additional CSS" in "Advanced Settings": margin-left: 0px !important; object-fit: initial !important;

It worked for Chrome at the time, and I see on the newest update for Ultrawidify on Chrome (4.4.10.1) that this was an issue that was fixed. However, it doesn't seem to be working on Microsoft Edge for some reason (which still shows Ultrawidify as version 4.4.92). I'm not sure if there is a fix that's possible or any help that could be provided, but I would appreciate it if there is. Thank you!

**Comment by tamius-han** [comment]
Key takeaways:

* Edge is fucking garbage
* Use Chrome or Firefox
* This is issue with Edge browser, more or less

Full rant will pop up in #117 in about an hour, pictures and all.
