### ISSUE TITLE
[Chrome] Video disappears after exiting fullscreen on youtube

### ISSUE THREAD

**Issue by memehammad** [tamius-han/ultrawidify#133]
has been happening for a few days with every video i watch, pressing r fixes the issue until I enter and exit fullscreen again.

**Comment by memehammad** [comment]
This only seems to happen when Chrome is snapped to the left / right side on my screen, when taking up the whole screen everything works fine.

**Comment by tamius-han** [comment]
Okay, I'm gonna need some more info here.

* Ultrawidify version?

* Go to youtube and snap the chrome window to the left or right side of the screen. Press F12 and switch to the console tab. If you see anything that looks like this:

![image](https://user-images.githubusercontent.com/12505802/107124358-c2ace200-68a3-11eb-9549-dab6038b2e21.png)

Just ignore it. Whack the 'clear console' button — ![image](https://user-images.githubusercontent.com/12505802/107124364-d2c4c180-68a3-11eb-9fd8-5d1cc0144301.png) this one, just so you have a clean slate.

Then switch to fullscreen or back. Do you get any errors or other things in the console after switching to/from full screen?

**Comment by memehammad** [comment]
I'm using version 4.5.3 and this shows up when I enter and exit fullscreen
![Screenshot_518](https://user-images.githubusercontent.com/39221228/107127339-c21d4700-68b5-11eb-8a25-af5eed4261de.png)

**Comment by tamius-han** [comment]
Well that's less helpful than I hoped. Seems like everything is working without any major problems that would be easy to fix.

Quick questions while I'm figuring out how to handle the issue:

* Does the issue happen when switching from fullscreen to theater mode?
* What kind of CPU do you have?

**Comment by memehammad** [comment]
The picture doesnt disappear, however it moves down a bit
![Screenshot_523](https://user-images.githubusercontent.com/39221228/107264905-de4eee80-6a43-11eb-88be-c0d16f0ed1b3.png)
My current CPU is a Ryzen 9 5900x

**Comment by tamius-han** [comment]
This better not be the case of "processor too fast, observers get triggered too soon." I've got another favour to ask:

1. Download this and unzip it to some directory (current version of Ultrawidify, except with a bit more logging):

[Ultrawidify-testing-2102.08.320-chrome.zip](https://github.com/tamius-han/ultrawidify/files/5946717/Ultrawidify-testing-2102.08.320-chrome.zip)

2. Head to `chrome://extensions` and disable chrome store version of Ultrawidify

3. Flip this switch on:

![image](https://user-images.githubusercontent.com/12505802/107279365-3d6a2e80-6a57-11eb-867e-e2f0b7729027.png)

4. Click 'load unpacked' and navigate to where you extracted unzipped version of ultrawidify. 

5. You know the drill. Go watch some videos. Switch to fullscreen, open the console, clear the console, switch back to desktop. I am mostly interested into everything that comes after the first `offsets are incorrect` message (there may be more than one), and the last few messages before it:

![image](https://user-images.githubusercontent.com/12505802/107280187-490a2500-6a58-11eb-817d-fc07f51aded2.png)

![image](https://user-images.githubusercontent.com/12505802/107280034-19f3b380-6a58-11eb-9bb5-7bf36ad590af.png)

**Comment by memehammad** [comment]
Sorry for the late reply.
The issue doesnt seem to occur when using the version for testing, however the video takes like 2 seconds to switch to fullscreen. 
These are the errors that I get:
![Screenshot_547](https://user-images.githubusercontent.com/39221228/108636397-4ad6de00-7485-11eb-99fa-e9c0a8a8a3b3.png)
![Screenshot_545](https://user-images.githubusercontent.com/39221228/108636398-4b6f7480-7485-11eb-9b49-487a7e149b5c.png)

**Comment by tamius-han** [comment]
> The issue doesnt seem to occur when using the version for testing,

Does it still happen on 4.5.3.1 (which was released earlier this week, it is possible that Chrome hasn't updated it yet for you)?

The second screenshot is a minor oof, though.

**Comment by memehammad** [comment]
Yeah, it still happens on the newest version.
"processor too fast, observers get triggered too soon." seems to be the issue tho, when I throttle the cpu to 600mhz everything works fine lol

**Comment by tamius-han** [comment]
I think the thing I'm getting on BBC is rather similar to what's being described here:

* video is offset after switching from fullscreen

So don't mind me, I'm just posting some links for later reference:

[Perseverence landing (actual footage, not cgi)](https://www.bbc.com/news/science-environment-56158928)

**Comment by tamius-han** [comment]
Whew, should be finally fixed as of 5.0.0+ (but I can never be 100% sure).

&nbsp;

&nbsp;

### Technical details for people who want technical details.

Long story short: apparently you can actually have dimensions of an object change without MutationObserver getting triggered.

Solution: ditched MutationObserver for ResizeObserver.

This is a rather new-ish option that was considered very "experimental don't use for reals" back when I was implementing observers, but all major browsers have been supporting it for a year or two now so ...

Seems to work like a charm.
