### ISSUE TITLE
"Letterbox misalignment threshold" and "Aspect ratio change threshold", same variable "allowedMisaligned"

### ISSUE THREAD

**Issue by DJGoo** [tamius-han/ultrawidify#134]
**Describe the bug**
The settings "Letterbox misalignment threshold" and "Aspect ratio change threshold" both point to the same variable "allowedMisaligned". effectively forcing them to be the same value.

**To Reproduce**
Change the AR variance or the AR misalignment value and look in advanced settings. 

**Expected behaviour**
Since these options point to the same variable, they cannot be set separately, limiting what a user can do. Independent variables would allow simultaneous high aspect ratio misalignment tolerance and low/no required variance in aspect ratio for change.

**Browser and OS**
 * Browser/browser version: Chrome Canary/90.0.4410.2
 * Operating system: Windows 10 Pro 20H2 64x
 * Ultrawidify version:4.5.3

**Additional info**
Otherwise, Ultrawidify runs well and performs to expectations, thanks for the great extension, I really appreciate the work it takes.
PS: Sorry if this has previously been submitted.

**Comment by tamius-han** [comment]
Given this appears to be a fairly small issue, I'll probably just kick that can can down the road, _after_ I'm done with my typescript and gui experiments.

**Comment by tamius-han** [comment]
Oh yeah, it gets worse than that.

They did point to the same variable in the gui, but not in the actual code. Which means that letterbox misalignment always took the default value ... 

... and that is actually fine, because it's much less of an issue than I initially thought.
