### ISSUE TITLE
Ultrawidify causing Reddit to go blank when viewing a video from Imgur

### ISSUE THREAD

**Issue by blefev** [tamius-han/ultrawidify#137]
**Describe the bug**

When viewing a video such as [this one](https://www.reddit.com/r/gifs/comments/m32c87/mornings_in_norway/) on Reddit, everything in the viewport goes blank. When viewing the video directly in the post, the entire viewport goes blank. When viewing the video from a plugin like Imagezoom+, everything behind the Imagezoom+ panel goes blank. 

This still occurs on the post page even if Imagezoom+ is disabled.

Even if "Enable Extension" and "Enable Autodetection" are disabled, the issue still occurs. The only way to prevent it is by disabling the extension from Firefox, or to uninstall it.

**To Reproduce**

1. Have Ultrawidify installed
2. View a video from Imgur on Reddit

**Expected behavior**

Not go blank, and respect disabled settings.

**Screenshots**
A picture is worth a thousand words. If Ultrawidify scales a video in an improper way, please include a screenshot of that.

![Ultrawidify-bug-reddit-hoverzoom2](https://user-images.githubusercontent.com/21296111/110972915-c9eb6380-8319-11eb-914b-c1141897e577.gif)

![Ultrawidify-bug-reddit2](https://user-images.githubusercontent.com/21296111/110973611-affe5080-831a-11eb-9ab5-d98d00422e75.gif)

**Browser and OS**
 * Browser/browser version:  Firefox 86.0.1
 * Operating system: Windows 10
 * Ultrawidify version: 4.5.3.1

**Additional info**
Any other things you want to say.

Other extensions installed:
-uBlock Origin
-LastPass (not for much longer, though)
-HTTPS Everywhere
-Stylus
-Privacy
-Imagezoom+
-Simple Translate

**Comment by tamius-han** [comment]
I see a dark mode, but I don't see RES on your extension list. How are you getting dark mode on old reddit?

**Comment by blefev** [comment]
I have that style through Stylus. And what do you know - it appears to be Stylus interacting with Ultrawidify that's causing the problem. Mystery solved. I thought I had tried it before with everything else disabled but I was wrong. Tried disabling it and it worked. I tried a different style too and it works, so something is just wrong with the theme I was using.

Thank you.
