### ISSUE TITLE
Nightly Builds Website Is Down

### ISSUE THREAD

**Issue by Insan1ty0ne** [tamius-han/ultrawidify#139]
**Describe the bug**
The Nightly Builds website is down. It reports "This site can’t be reached. stuff.lionsarch.tamius.net took too long to respond. ERR_CONNECTION_TIMED_OUT"

**To Reproduce**
Click this link: [https://stuff.lionsarch.tamius.net/ultrawidify/nightly/](url)

**Expected behavior**
The website should be up so we can access the latest builds.

**Screenshots**
N/A

**Browser and OS**
 * Browser/browser version: Google Chrome Version 91.0.4449.3 (Official Build) dev (64-bit)
 * Operating system: Windows 10 (Build 19042.867)
 * Ultrawidify version: 2102.19.456

**Additional info**
N/A

**Comment by tamius-han** [comment]
That particular machine (and a few others) is currently offline for ... reasons that the internet doesn't need to know.

It's probably going to remain offline until after easter (though this may happen quicker depending on how a few things turn out).

**Comment by Insan1ty0ne** [comment]
> That particular machine (and a few others) is currently offline for ... reasons that the internet doesn't need to know.
> 
> It's probably going to remain offline until after easter (though this may happen quicker depending on how a few things turn out).

Appreciate the reply! Hope all is well. I will look forward to testing future builds after Easter.

**Comment by tamius-han** [comment]
This has been a bit faster than I expected, but the site is up as of this past weekend.
