### ISSUE TITLE
Extension stretches video incorrectly in full screen

### ISSUE THREAD

**Issue by tamius-han** [tamius-han/ultrawidify#144]
I misidentified the issue iamtau had, so I'm moving the initial issue to #148 and making this issue about the hardware acceleration thingy (& related shit).

Quick bug demo:
![slika](https://user-images.githubusercontent.com/12505802/114618605-d280e200-9ca9-11eb-9ad3-916caa65684d.png)

We already know what's causing this bug:
* there's a nVidia hardware acceleration bug that all Chromium-based browsers have
* problem is that chrome can't handle `transform: scale(x)` correctly in full screen
* and it's apparently not strictly limited to nVidia hardware, either, because as we will see in the comments ...

**Comment by markusd1984** [comment]
I added the extension yesterday and it didn't work at all for me, on two laptops, none of the cropping mode buttons had any effect and neither keyboard short cuts while enabled.

Which is why i switched to super convenient Zoom to Fill button for YT and also UltraVideo due to keyboard shortcuts. 

I'd love to try Ultrawidify for more flexibility and features, especially as I'm desperate for an alignment option to switch between cropping the top or bottom part rather then only zoom in crop.for 21:9, which I have a feeling could be added to Ultrawidify.

**Comment by iamtau** [comment]
Hi, this is in relation with my comment on thread #132, and you'd asked to take a screenshot of the console. Attaching that below, since the issue I had of the video just getting stretched in fullscreen mode to 21:9 is still persistent.

![image](https://user-images.githubusercontent.com/39721921/114265196-1c996780-9a0d-11eb-83e8-d2a01f1d3c6a.png)

**Comment by tamius-han** [comment]
@iamtau 

Open the popup, go to advanced settings and check the following checkboxes:

![image](https://user-images.githubusercontent.com/12505802/114360221-12927880-9b75-11eb-9182-316a73271b88.png)

If your issue isn't resolved, try:

* Uncheck the "limit zoom only if in fullscreen" checkbox.

* If that doesn't work, try reducing the 'limit zoom to %' number a bit (try 0.99, if that fails try 0.95, if that fails try 0.9. If any of these work, try to mess with the number until you find the highest number that works)

If neither of the two options work, disable hardware acceleration. 


In any case, if checking the checkboxes OR disabling hardware acceleration fixes your problem, please consider reporting your issue to Google. Presss alt+shift+i. In the 'describe your issue' box, enter this:

> If — while in fullscreen mode — CSS property transform: scale(x) causes video to be both taller and wider than the monitor, the video will be stretched to exactly fill the monitor. This is incorrect behaviour.
> * If video and monitor are of different aspect ratios, aspect ratio of the video will not be preserved. (Expectation: transform: scale(x) should preserve aspect ratio if only one factor is provided)
> * transform: scale(x) will not scale video to a size that’s strictly bigger than the monitor. (Expectation: it should do so if x is big enough)
> This issue only happens when the following are met:
> * Windows
> * Full screen and watching a video
> * Hardware acceleration: enabled
> * nVidia GPU
> * Console: closed or in detached window. If console is opened and docked to the side, the problem does not appear.
> * transform: scale(x) or transform: scale(x,y) is used to scale the video to a size bigger than the monitor

**Comment by tamius-han** [comment]
Whoops, you said you don't have a nVidia GPU, which is _sus af_. Please disregard the bit about reporting the bug to google.

Also, please provide a screenshot of the issue happening. I have been making a few assumptions about what's happening on your end, and I want to be sure the issue you're having is the one I sense you're having.

You can take a screenshot with print screen and then just paste it into the comment box, and github should add the screenshot to the comment.

**Comment by VladWinner** [comment]
These settings work for me with [this sample video](https://www.youtube.com/watch?v=eQwBAfJXz7Y):
![image](https://user-images.githubusercontent.com/13555921/114597013-f25bda00-9c98-11eb-835a-a974fa58aed2.png)
Also no problems at 0,95
My PC: Windows 10, Chromium, GTX 970

But (!) on [this video](https://www.youtube.com/watch?v=zQznRU_GYQg), the extension works even correctly with the standard settings only (0,997).

If I set settings as at the top of my text, I will get the following frames with borders and offset to the left
instead of this corrected result:
![image](https://user-images.githubusercontent.com/13555921/114597347-57afcb00-9c99-11eb-957f-ae1c9324bcbb.png)

Activation or deactivation of the extension also occurs in random order on same settings set.

**Comment by iamtau** [comment]
> Whoops, you said you don't have a nVidia GPU, which is _sus af_.

l have a laptop that runs on an AMD CPU and only have integrated graphics, is there a reason why you feel my issue could be due to nVidia graphics?
 
> Also, please provide a screenshot of the issue happening. I have been making a few assumptions about what's happening on your end, and I want to be sure the issue you're having is the one I sense you're having.
> 
> You can take a screenshot with print screen and then just paste it into the comment box, and github should add the screenshot to the comment.

Here's the screenshot of the video without the fit to width applied:
![image](https://user-images.githubusercontent.com/39721921/114611712-f4d12a80-9cbe-11eb-80c3-9ce76ea7c3da.png)

Here's a screenshot after Fit to Width is applied:
![image](https://user-images.githubusercontent.com/39721921/114611918-20ecab80-9cbf-11eb-8e03-470cefc4ad93.png)

**Comment by iamtau** [comment]
Okay, so I tried playing around with the Limit zoom options, and while in Fullscreen, turning off Limit zoom only while in fullscreen with Limit Zoom set to 0.997 works, and turning off Limit zoom entirely works when I'm not in fullscreen. There's no solution that seems to work for both scenarios, but this will do for now at least!

**Comment by tamius-han** [comment]
> l have a laptop that runs on an AMD CPU and only has integrated graphics, is there a reason why you feel my issue could be due to Nvidia graphics?

I don't feel that your issue is due to nVidia graphics (sorry if I came across as implying you're secretly running nVidia GPU), it's just that lately, Chrome (all chromium-related browsers, actually) browsers have a bug.

So far, this bug has always happened on nVidia, I've had a talk with a few people who use AMD/Intel (discrete or integrated, doesn't matter), and they said they aren't experiencing this issue. So pardon me for forgetting you're not using nVidia. At 2230 on a workday, it's a very easy thing to overlook.

# The Chrome Bug

If you're in fullscreen and you have a `<video>` element that is both taller than your monitor _and_ wider than your monitor¹, Chrome will stretch the video to be exactly the same size as your monitor.

This is _very probably_ a bug with your browser, not with the extension. Other possible culprits: Windows, your driver (but really Windows, if you're using Windows 10). 

If you want to be completely sure this is truly a browser bug, disable ultrawidify (from `chrome://extensions` page, not just via popup). After you disabled ultrawidify, open a youtube video (any 16:9 video will do). open browser console (press F12), select `console` tab. Paste this into the browser console, press enter:

```js
setTimeout(
  () => document.getElementsByTagName('video')[0].style.transform = 'scale(10)',
  10000
);
```

Close the console, put the video in fullscreen, wait 10 seconds (you need to close the console and fullscreen the video before 10s are up).

You _should_ get the same result as with Ultrawidify, because that's what ultrawidify does (unless you also do basic or hybrid stretch, but you aren't using that). 

## Further descent into madness: I am so fucking done with this shit edition

My comment has been long enough so far, so a brief history of this bug:

* second half of January 2020: I can reproduce this bug with a single line of code. In Chrome and Edge, but — curiously enough — not Opera.
* february 2020: rumor has it that the bug is fixed. I do nothing, because people are reporting same behaviour as you on reddit _well into March_. The rumor about this bug being fixed is obviously wrong (but I cannot reproduce the bug anymore?)
* April 2020, easter weekend: I decide to take out the zoom limit for Chrome while still keeping it for Edge — as the issue [seemed to be fixed in Chrome but not in Edge](https://streamable.com/g08scw). The issue now also happens on Opera. _Curiously enough, it only happens on my 2080Ti, but not on 965m._ 
* _literally the monday after_: chrome starts stretching video in fullscreen on my 2080ti again, making me look like a fucking retard.
* last week: you say you're getting issue on not-nvidia, and someone else said they're getting this issue on non-rtx
* today: the stretching issue is no longer happening for me at all, in any Chromium-based browser (Chrome, Edge, Opera, Opera Next).

### Testing methodology

1. Disable ultrawidify
2. You've seen the javascript snippet earlier. I've been triggering this bug with the javascript snippet rather than with ultrawidify.

# This summary might not make a lot of sense

I am aware that all of the above is more 'stream of consciousness' kind of rant and less of a proper explanation. In my defence, it's past midnight right now. I should get some sleep.


—————————————

[1] I slightly lied. The bug starts to manifest when the video is taller and (usually) a few pixels shy of being as wide as the monitor (it is assumed that same thing would happen if the video was wider and a few pixels shy of being as tall as the monitor, but nobody's tested or reported that yet).

**Comment by tamius-han** [comment]
@VladWinner 

> If I set settings as at the top of my text, I will get the following frames with borders and offset to the left
instead of this corrected result:

This is correct behaviour. The extension ensures that no matter what crop you select, the extension always keeps small black border at the sides of the video (unless video file aspect ratio roughly matches your monitor).

If you make the "limit to % of width" number smaller, the black borders at the sides will get wider.

As I said earlier: this appears to be either a browser, GPU driver, or a Windows bug that affects all Chromium-based browsers, and all my extension can do is to prevent the video from being zoomed in enough for this bug to kick in.





...

Another option — if the 'limit zoom' option doesn't work _or_ if you don't like how it works is to disable hardware acceleration. So far, disabling hardware acceleration _is_ the one thing that pretty much guarantees that this bug will no longer happen. 

However, disabling hardware acceleration is not reccomended. It's a bad solution that can (and, according to some people, absolutely does) result in stuttery video playback on higher resolutions.

**Comment by VladWinner** [comment]
@tamius-han Thank you for the detailed answer! The aspect ratio of my monitor is 21:9. I said about some kind of bug when black bars are not cut off from the source (like without extension), and the image itself is shifted to the left instead of center. Sometimes this bug can not be observed and the plugin will work 100% correctly: there will be no blackbars on the left and right, and there will be a minimum number of blackbars on the top and bottom.
![Screenshot_20210414-014127](https://user-images.githubusercontent.com/13555921/114630689-d1f54500-9cc3-11eb-9475-7cbbf7c452fb.png)
I can not say exactly why the plugin works unstable with the same videos on YouTube (it may work for now, but it will stop cutting off blackbars the next time it is launched).

**Comment by tamius-han** [comment]
@VladWinner happened to me _once_, but never before and — after clicking through a few videos — never again. 

How often does it happen to you?

**Comment by VladWinner** [comment]
> @VladWinner happened to me _once_, but never before and — after clicking through a few videos — never again.
> 
> How often does it happen to you?

It's all situational. It occurs once in 10-15 videos.
About overall working of extension: It may not work 3-5 times, but then it will work all the time until you close the browser. Or it can work immediately.

**Comment by tamius-han** [comment]
**FURTHER UPDATES** re: chrome bug

Upon news that the issue is happening on AMD (APUs), I've taken another look at other devices. It appears that the Chrome issue has also infected my Surface Pro 7 (and I have managed to get my hands on another intel-integrated-only laptop which also exhibits the issue). 

Turns out that the issue is very much no longer nvidia-only.

Yikes.

Another fun fact — `trasnform: scale(big)` (for sufficiently big values of big, usually 10 and above does the job) will crash Chrome's hardware acceleration until browser is restarted.

I am really tempted to do a faux `transform: scale(1000)` for a single frame, immediately after user switches to full screen for the first time in that session — but I'm prolly not gonna do it because some people will likely get mad about videos stuttering when hardware acceleration dies.

**Comment by moriel5** [comment]
I'm not sure if this is the same but, however on my Radeon HD 6950, on Linux (Solus), with both Firefox Nightly and Eve Dev, I am getting a weird situation, specifically with Ultrawidify on, where videos do not stretch or crop, but literally show up at their full resolution, disregarding my monitor's resolution, and every single element in the page, many times showing up on the same exact spot as the or elements (as shown [here](https://user-images.githubusercontent.com/20175297/115156112-518f6500-a072-11eb-9587-fff94e9a0625.png), the same exact thing also happens on Firefox).

**Comment by tamius-han** [comment]
> I'm not sure if this is the same but, 

No, that's a different issue bit I'm too done with GLS not knowing what a doorbell is to care about opening a separate issue.

What happens if you check this option:
![image](https://user-images.githubusercontent.com/12505802/115625029-c5906e00-a2fb-11eb-9a00-53a94e735a94.png)

Also, can you press F12, paste this into browser console and screenshot what you get back?

```js
console.log(
`window inner dimensions: ${window.innerWidth} x ${window.innerHeight}\nscreen size:${ screen.width} x ${screen.height}`
)
```

Example:
![image](https://user-images.githubusercontent.com/12505802/115625599-92021380-a2fc-11eb-82dc-bb6dbda49554.png)

**Comment by moriel5** [comment]
> > I'm not sure if this is the same but,
> 
> No, that's a different issue bit I'm too done with GLS not knowing what a doorbell is to care about opening a separate issue.
> 
> What happens if you check this option:
> ![image](https://user-images.githubusercontent.com/12505802/115625029-c5906e00-a2fb-11eb-9a00-53a94e735a94.png)
> 
> Also, can you press F12, paste this into browser console and screenshot what you get back?
> 
> ```js
> console.log(
> `window inner dimensions: ${window.innerWidth} x ${window.innerHeight}\nscreen size:${ screen.width} x ${screen.height}`
> )
> ```
> 
> Example:
> ![image](https://user-images.githubusercontent.com/12505802/115625599-92021380-a2fc-11eb-82dc-bb6dbda49554.png)

I have no idea what GLS is, though I'd rather post a new issue if this is a separate bug, so I shall do so right now.

**Comment by tamius-han** [comment]
>  have no idea what GLS is, though I'd rather post a new issue if this is a separate bug, so I shall do so right now.

A shit-tier delivery service. Sorry 'bout that, it was a bit of an unrelated rant. Thanks for making a separate issue.

**Comment by zHalfinity** [comment]
I had the same issue on Brave on Windows with GTX980 and I fixed it with setting use-angle flag to OpenGL
```
Choose ANGLE graphics backend
Choose the graphics backend for ANGLE. D3D11 is used on most Windows computers by default. Using the OpenGL driver as the graphics backend may result in higher performance in some graphics-heavy applications, particularly on NVIDIA GPUs. It can increase battery and memory usage of video playback. – Windows

[#use-angle](chrome://flags/#use-angle)
```

**Comment by heliosfa** [comment]
I don't use ultrawidify, but I came across this thread as I have been running into this issue on native chrome on Netflix. 

> I had the same issue on Brave on Windows with GTX980 and I fixed it with setting use-angle flag to OpenGL
> 
> ```
> [#use-angle](chrome://flags/#use-angle)
> ```

This workaround works when setting the backend to OpenGL or D3D9.
Setting it to D3D11 or D3D11on12 causes the stretching issue.

**Comment by hsinyu-chen** [comment]
> I don't use ultrawidify, but I came across this thread as I have been running into this issue on native chrome on Netflix. I am using nVidia GPUs on multiple systems (this happens on RTX4090, RTX3080ti, RTX3070 and RTX2070).
> 
> > I had the same issue on Brave on Windows with GTX980 and I fixed it with setting use-angle flag to OpenGL
> > ```
> > [#use-angle](chrome://flags/#use-angle)
> > ```
> 
> This workaround works when setting the backend to OpenGL or D3D9. Setting it to D3D11 or D3D11on12 causes the stretching issue.

but switch to old graphics backend make netflix / disney+ only stream 480p , and also disable features like nvdia vsr
where can we report this issue to Chromium team?

**Comment by tamius-han** [comment]
> and also disable features like nvdia vsr
where can we report this issue to Chromium team?

https://bugs.chromium.org/p/chromium/issues/list

Note that the last time Chrome had this issue, it took about a year (at least) for the issue to get fixed. Other browsers get the fixes even later.

**Comment by hsinyu-chen** [comment]
> > and also disable features like nvdia vsr
> > where can we report this issue to Chromium team?
> 
> https://bugs.chromium.org/p/chromium/issues/list
> 
> Note that the last time Chrome had this issue, it took about a year (at least) for the issue to get fixed. Other browsers get the fixes even later.

when I about to post issue and try reproduce on disney+ on edge with following css:
```css
:fullscreen video{
    position: fixed;
    top: 0;
    left: 0;
    transform-origin: center center;
    transform: scale(1.35);
}
```
and it works again ,last time (few month ago) I test it's not,
no matter what I use (hight, transfrom, object-fit...) , so confuse

**Comment by tamius-han** [comment]
Did your browser get updated in the mean time? Because that would be one thing that would explain it.
