### ISSUE TITLE
Extension appears to not work at all on some people's hardware.

### ISSUE THREAD

**Issue by tamius-han** [tamius-han/ultrawidify#148]
**Describe the bug**
Some people claim that extension no longer works, _period_, on their hardware.

People who say the extension isn't quite working report using:
* integrated GPU

**To Reproduce**
Not provided. Extension apparently suddenly got borked, and remains borked even after an install. 
I haven't managed to reproduce this issue on my machine yet.

**Screenshots**
A report via email attached this image, stating that extension didn't want to fit width.

![slika](https://user-images.githubusercontent.com/12505802/114090539-daaadd00-98b7-11eb-9462-c6892bb18066.png)

**Browser and OS**
 * Browser/browser version: Chrome (unknown version, presumed newest)
 * Operating system: 
 * Ultrawidify version: 5.0.0 onwards

**Comment by zHalfinity** [comment]
I had the same issue on Brave on Windows with GTX980 and I fixed it with setting use-angle flag to OpenGL
```
Choose ANGLE graphics backend
Choose the graphics backend for ANGLE. D3D11 is used on most Windows computers by default. Using the OpenGL driver as the graphics backend may result in higher performance in some graphics-heavy applications, particularly on NVIDIA GPUs. It can increase battery and memory usage of video playback. – Windows

[#use-angle](chrome://flags/#use-angle)
```
