### ISSUE TITLE
Improper Scaling of Videos

### ISSUE THREAD

**Issue by moriel5** [tamius-han/ultrawidify#151]
**Describe the bug**
Videos get scaled to their resolutions, ignoring monitor resolution, as well as all other elements on the page, showing in the same exact place, when Ultrawidify is enabled.
This happens on both Firefox and Edge, on all websites.

**To Reproduce**
1. Enable Ultrawidify.
2. Proceed to open a page with a video in it.

**Expected behavior**
What do you think should happen instead?

**Screenshots**
![image](https://user-images.githubusercontent.com/20175297/115630073-16a85e00-a30c-11eb-936a-61a2c952ae74.png)

**Browser and OS**
 * Browser/browser version: Firefox (Nightly), Edge (Dev)
 * Operating system: Linux (Solus)
 * Ultrawidify version: 5.0.2

**Additional info**
Disabling usage of monitor AR in fullscreen does not affect this.

Results of dimension check in the console brings this:
![image](https://user-images.githubusercontent.com/20175297/115630044-0bedc900-a30c-11eb-91ab-e65750dabf74.png)

**Comment by moriel5** [comment]
Moving from issue #144 to prevent confusion.

**Comment by tamius-han** [comment]
> Disabling usage of monitor AR in fullscreen does not affect this.

> [console screenshot]

Okay then, so the new way to handle fullscreen videos isn't to blame.

Further questions:

* do you have any other extensions that work on youtube
* X or wayland?

**Comment by moriel5** [comment]
- I'm not really trying to run this on YouTube nowadays, since I just redirect to Invidious (and will be moving over to Piped in the future, that screenshot was from a bug report for the Piped developer), however I have Privacy Redirector active.
- X. The Budgie DE doesn`t support Wayland yet.

**Comment by tamius-han** [comment]
> I'm not really trying to run this on YouTube nowadays, since I just redirect to Invidious (and will be moving over to Piped in the future, that screenshot was from a bug report for the Piped developer)

Oh _right_. It's in the URL in the screenshot, too. Shoulda stop going on github at midnight. 

Anyway, complaining aside — try manually specifying the player. Do things continue to break if you do this?
![image](https://user-images.githubusercontent.com/12505802/115678275-a15f7c00-a351-11eb-855e-9bdf96dd9db5.png)

**Comment by tamius-han** [comment]
Well that's awkward, my previous screenshot broke after posting for some reason.

Anyway — in popup, go to advanced settings > `× manually specify player` and `× player is n-th parent of video:   1`

![image](https://user-images.githubusercontent.com/12505802/115678594-fa2f1480-a351-11eb-9c44-603a917b18f9.png)

**Comment by moriel5** [comment]
I'll try doing so immediately when on my desktop.

And don't worry, I know how that feels, since my time-keeping skills are pretty bad (case in point, it was after midnight for me), and I have made my own half-asleep rants in the past because of that.
