### ISSUE TITLE
Space outside video appears white in plex

### ISSUE THREAD

**Issue by Liquid-Banana** [tamius-han/ultrawidify#158]
**Describe the bug**
Your extension works great in on the plex site, but it makes the area around the video white instead of black, this is not very nice while watching a movie.

**Screenshots**
With extension enabled:
![image](https://user-images.githubusercontent.com/52746821/123830483-a0276e00-d903-11eb-9ac5-3228dae06f6a.png)
Without extension enabled:
![image](https://user-images.githubusercontent.com/52746821/123830622-c1885a00-d903-11eb-96e5-b580cd71a191.png)

**Browser and OS**
 * Chrome
 * Windows 10
 * Ultrawidify version: 5.0.4

**Comment by tamius-han** [comment]
In 'advanced settings', try doing this:

![slika](https://user-images.githubusercontent.com/12505802/124395213-27f5e980-dd03-11eb-807a-338144e28d78.png)

**Comment by Liquid-Banana** [comment]
This worked!
its now nice and black

this is indeed a self hosted plex server
