### ISSUE TITLE
always float: Right

### ISSUE THREAD

**Issue by thisVioletHydra** [tamius-han/ultrawidify#160]
**Describe the bug**
Describe what happened. Don't forget to mention which site you were on (reddit, netflix, youtube). If issue only happens with certain videos, please provide links with timestamps.

**To Reproduce**
What did you do to make it happen? 

**Expected behavior**
What do you think should happen instead?

**Screenshots**
A picture is worth a thousand words. If Ultrawidify scales a video in an improper way, please include a screenshot of that.

![image](https://user-images.githubusercontent.com/11839238/125662028-cfa612f0-7af8-4e4d-bb44-f008476a9729.png)
![image](https://user-images.githubusercontent.com/11839238/125662073-c496cb99-f0ec-4a30-9121-9f9fa3b0418a.png)

**Browser and OS**
 * Browser/browser version: latest chrome
 * Operating system: win 10 x64
 * Ultrawidify version: master

**Additional info**
Any other things you want to say.

**Comment by thisVioletHydra** [comment]
if i change css in 'video' tag, bug is gone 
![image](https://user-images.githubusercontent.com/11839238/125663141-cd828ec8-6a78-4d03-be97-c3390dd88e0b.png)

**Comment by tamius-han** [comment]
Hi, 

thanks for report.

Open the extension popup, go to `Advanced settings → Video detection settings` and paste this into the 'Additional style for video element' box:

```
position: absolute !important;
```

![Screenshot_20210714_210745](https://user-images.githubusercontent.com/12505802/125678780-f9e60df4-a1b2-4f5a-873a-ffbb1596aa5a.png)

This should apply `position: absolute` to the video element without you having to fiddle around with the console (at least until the site goes and re-designs their video player).

**Comment by thisVioletHydra** [comment]
> Hi,
> 
> thanks for report.
> 
> Open the extension popup, go to `Advanced settings → Video detection settings` and paste this into the 'Additional style for video element' box:
> 
> ```
> position: absolute !important;
> ```
> 
> ![Screenshot_20210714_210745](https://user-images.githubusercontent.com/12505802/125678780-f9e60df4-a1b2-4f5a-873a-ffbb1596aa5a.png)
> 
> This should apply `position: absolute` to the video element without you having to fiddle around with the console (at least until the site goes and re-designs their video player).

![image](https://user-images.githubusercontent.com/11839238/125708194-f32b8a44-0cc9-4843-ae79-1296fa4b0f1a.png)

**Comment by thisVioletHydra** [comment]
!up, i forget save setting... 
![image](https://user-images.githubusercontent.com/11839238/125708386-d8245f93-b47e-4456-a9b9-2ebc175298de.png)
all work thx

**Comment by Gr33nHood** [comment]
![image](https://github.com/tamius-han/ultrawidify/assets/102728244/9a37e02e-61f4-42d2-908e-9ee5b216af98)

does not work for me at all 
without my youtube account it work very well after login I get this in every browser I use brave or firefox
