### ISSUE TITLE
[YouTube] Music uploads are left aligned regardless of the alignment setting 

### ISSUE THREAD

**Issue by dio-gh** [tamius-han/ultrawidify#162]
Automated music uploads on YouTube like [this one](https://www.youtube.com/watch?v=VEe_yIbW64w) have a square aspect ratio, as the album cover is the video content. However, despite setting the video alignment option to centered site-wide, the video remains left aligned. Even the per-page video alignment keeps it that way. Changing the video alignment option does seem to have an effect, but the video content immediately jumps back to the left regardless of my setting.

![image](https://user-images.githubusercontent.com/10439488/129519976-21988002-2ca7-404d-846a-00aba50f2ce4.png)

 * Browser/browser version: Google Chrome 92.0.4515.131
 * Operating system: Windows 10
 * Ultrawidify version: latest from the Chrome Web Store (5.0.6)

**Comment by tamius-han** [comment]
Notes to self: requires some rather special conditions.

* Window must be sufficiently wide
* Window must be sufficiently short (1080p and 1440p ultrawide)
* Normal player only, theater mode unaffected

**Comment by tamius-han** [comment]
Hi,

the issue should be fixed. It's going to take a few days to about a week for Chrome Web Store (et al) to send out the update. 

**If you don't want to wait,** you can go to youtube, open the popup, switch to the _Advanced Settings_ tab.  Check the _Manually specify player_ checkbox, click 'advanced mode' thing next to it. Then paste the following into the _Query selectors for player:_ textbox:

```
#movie_player, #player, #c4-player
```

Then click 'save' and close the popup. 

Thanks for reporting the issue.

**Comment by dio-gh** [comment]
Hi,

Glad to hear! I'll test it soon and report back if I find any issues. I noticed that it also used to happen on "shorts"-type videos, hopefully that's fixed too.

Thanks for the swift fix.
