### ISSUE TITLE
[YouTube] Ultrawidify randomly fails to attach to the player

### ISSUE THREAD

**Issue by dio-gh** [tamius-han/ultrawidify#165]
Somewhat often Ultrawidify fails to attach on YouTube, meaning I'm unable to control the aspect ratio until a luckier reload, despite having the addon in manual control mode.

As described, this is a semi-random behavior, so reproducing it may be challenging. I've had the issue happen on many videos, most recent example would be [this](https://www.youtube.com/watch?v=0IzQ9DCffAg) one.

Personally however, I don't really think it's related to any specific video. I'd imagine it may be a conflict with other addons of mine, or a timing issue.

I'm using the latest stable version of Windows 10 Home, with Chrome 92.0.4515.159 (also latest). My Ultrawidify version is 5.0.7 (latest).

Other addons that I have installed and touch the site:
- uBlock Origin (version: 1.37.2, latest)
- AdBlock Plus (version: 3.11.1, latest)

I experience the issue most often when I've been consuming YouTube content for an extended period of time without utilizing the addon, and then enabling Teather mode on a video, and attempting to use the addon. In my testing however, this wasn't a surefire way to repro still.

If I can help in any way, let me know. I might take a day or so to answer, but I'll stick around.

**Comment by dio-gh** [comment]
Alternatively, some logging could be pushed to mainline, so I could look at the JS console when things are not working.

**Comment by dio-gh** [comment]
**Small update**: I found that there's actually some pieces of info printed to the JS console when it fails. Seems like my intuition is at least partially right:

![image](https://user-images.githubusercontent.com/10439488/130531840-f437661b-0adb-4772-b353-da70667f2208.png)

The addon fails to create and populate the `player` field:

![image](https://user-images.githubusercontent.com/10439488/130532515-dc7a9edd-0f41-435f-a37f-06aefb677d93.png)

So the call to a method of it fails. Call stack and code:

![image](https://user-images.githubusercontent.com/10439488/130532626-8b0b059c-fbff-4cf4-9fcd-b53b60f65a96.png)

I tried dumping the local vars, but I'm not really experienced with JS, so I couldn't. I'm not really sure how the field is normally initialized, obviously the initialization fails somehow. I do see MutationObservers scattered everywhere, so that at least rules out timing issues. Will try looking further into it now, as long as I don't reload the page I can get the bug to trigger. :))

**Comment by tamius-han** [comment]
Well that's a fun one, I didn't actually think anything gets logged to the console so I spent my evening trying to get logging into an useful state instead.

Thanks, I'll look into this tomorrow or the day after.

**Comment by tamius-han** [comment]
I started and immediately gotten a fun week or two at work (+ some IOUs for my D&D campaigns). TL;DR of that work thing is "java sucks, give me back my typescript." But I digress.

There _is_ another problem that prevents me from doing the logger thing, because logger is _not_ going to catch the instances where the player doesn't exist.

While digging through my old code (or rather, UI redesign branch) I also got sidetracked by noticing some `window` object abuse, which might be a solution to the missing player issue. I've been investigating that for a bit, but haven't found anything yet.

I hope I can get that into the mainline _this_ week, because I've been informed over the weekend that another issue popped up with Netflix.

**Comment by tamius-han** [comment]
So here's status update:

* Coming to Firefox within a few hours
* Coming to Chrome within a few days
* Coming to Edge by the end of the week, probably

Basically, as soon as it pasess reviews. If you're willing to dabble with logging.

* The logger is back and functional. (Open popup -> "report a problem" -> "Show logger" (at the bottom of the popup)

![image](https://user-images.githubusercontent.com/12505802/133358446-6ee14174-d8bd-4292-b7bd-22361afe4ca7.png)

Not really a pinnacle of design, but hey. It registers clicks and it updates settings for what kind of stuff gets logged to console as soon as you click that save button (not to be confused for 'start logging'). 

* Configure appropriately. If there's no configuration there initially, click 'default config' button. For problems with things not working in theater mode, the relevant options that will produce useful logs are debug, init, keyboard, actionHandler, playerDetect, resizer, arDetect (and possibly periodicPlayerCheck under allowBlacklistedOrigins).

**Comment by dio-gh** [comment]
I'll see what I can do, thanks.

**Comment by dio-gh** [comment]
Just to post a heartbeat, I couldn't repro the issue ever since. Not sure if it has to do with any of the changes pushed since the original post though.

I don't like bugs like this, lol :p

**Comment by dio-gh** [comment]
Having used it several times since, I genuinely can't repro - which is great news! It seems like one of the minor fixes did fix this bug too.

Closing.

**Comment by tamius-han** [comment]
Nice to hear. If it happens again, feel free to re-open the issue.

Thanks for the help.
