### ISSUE TITLE
YouTube autodetection is broken on Firefox

### ISSUE THREAD

**Issue by saschanaz** [tamius-han/ultrawidify#166]
**Describe the bug**

https://www.youtube.com/watch?v=XqKbuEDvaf8 does not automatically crops to 21:9 anymore on Firefox 92

**To Reproduce**
Open the link and play it. It never crops the video without a manual step.

**Expected behavior**
It should crop the video

**Screenshots**

![image](https://user-images.githubusercontent.com/3396686/133862038-63d72465-9ac1-4914-9d45-132f926d1abe.png)

**Browser and OS**
 * Browser/browser version: Firefox 92
 * Operating system: Windows 11 22000.194
 * Ultrawidify version: 5.1.0

**Additional info**
I first confirmed it's broken on version 94. It was okay on version 92 then but after extension update it broke too.

**Comment by tamius-han** [comment]
This should be fixed with an update that will arrive sometime this week (as soon as the addon stores accept the new version and browsers update it). 

Thanks for reporting the issue.

**Comment by saschanaz** [comment]
AMO accepted and it works 👍
