### ISSUE TITLE
2.2.1 aspect ratio cropping mode shortcut

### ISSUE THREAD

**Issue by Phoenomenal** [tamius-han/ultrawidify#176]
Hello,
Is it possible to add 2.2.1 cropping mode shortcut ?   I noticed many movies and tv series started to use this aspect ratio (Wonder woman 1984,  Lost in the Space tv series,  Titans season 3  for example)   Without a manual zoom and  "Fit height"  not working in Ultrawidify  there are no option to properly fit this aspect ratio (in 18:9 there are still black bars on all sides and in 21:9 video a bit zoomed)

Titans season 3 on Netflix is good to test as it have black bars on all 4 sides of screen.

**Comment by tamius-han** [comment]
It is possible, in extension settings (proper, not popup).

Make sure to tick the 'show in popup' box and both 'save' buttons.

![slika](https://user-images.githubusercontent.com/12505802/150013527-00d614ee-ed27-4896-aeed-a7a14732a015.png)

Adding keyboard shortcut may be broken at the moment and may require poking around in the super advanced settings.

**Comment by Phoenomenal** [comment]
Works like a charm.  Thanks!!!

![image](https://user-images.githubusercontent.com/68902338/150017000-63238572-865b-460f-9ee4-4ec85a615971.png)
