### ISSUE TITLE
Video goes back to 16:9 on Youtube Google Chrome

### ISSUE THREAD

**Issue by Ruypbf** [tamius-han/ultrawidify#181]
So Ultrawidify was working, but now when I try to use it on youtube it changes the aspect ratio like it is supposed to do. But when i change to fullscreen it goes back to 16:9

**Comment by tamius-han** [comment]
Can I get a specific video (and the list of other extension you've installed?)

Because so far, it seems to work for me just fine for me on my suite of test videos.
