### ISSUE TITLE
Extension not working in YouTube

### ISSUE THREAD

**Issue by kaushiksv** [tamius-han/ultrawidify#192]
**Describe the bug**
The options _Site Settings_ and _Video Settings_  are both greyed out.

**To Reproduce**
Load any YouTube video, and click on the extension icon.

**Expected behavior**
Extension's basic functionality should work. (Options to adjust the aspect ratio should be available)

**Screenshots**
![image](https://user-images.githubusercontent.com/4756704/179351674-a6f83d2c-2a45-422c-9424-bfd349f048f1.png)

**Browser and OS**
 * Browser/browser version: Firefox 97.0 64 bit
 * Operating System: Ubuntu 20.04.3 LTS
 * Ultrawidify version: 5.1.1
 * Last Update: 20 September 2021

**Additional info**
 * User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0
 * Kernel: Linux 5.4.0-99-generic
 * Architecture: x86-64

**Comment by tamius-han** [comment]
Hi,

It appears that you disabled the extension in the popup. The option to enable/disable extension should be at the top of the popup, but (this section) appears to be missing from your popup for some reason:

![Screenshot_20220717_132708](https://user-images.githubusercontent.com/12505802/179395944-2b57c02a-393c-4728-a711-663161136a84.png)

Can you please export your settings and post the configuration? You can export settings on the extension's settings page:

![image](https://user-images.githubusercontent.com/12505802/179395814-c8aaab24-385f-43c3-9a0a-722e55e6ff5d.png)

**Comment by kaushiksv** [comment]
Hi,

Sorry for the late reply, I was bit caught up in work. The file is attached.

Thanks.

[ultrawidify-settings.json.txt](https://github.com/tamius-han/ultrawidify/files/9170004/ultrawidify-settings.json.txt)

**Comment by tamius-han** [comment]
> Sorry for the late reply, I was bit caught up in work. 

No problem, that happens to me _a lot_.

In the next few days, Ultrawidify should get an update that will fix the "missing" `Enable extension` button row in the popup:

![Screenshot_20220717_132708](https://user-images.githubusercontent.com/12505802/179395944-2b57c02a-393c-4728-a711-663161136a84.png)
_If you can see the highlighted option in your popup, then the extension got updated! If the extension got updated but you still don't see this option, then we've got another problem. Please report back if 5.1.2 doesn't fix the issue for you._

The settings you want in the popup are:
* "Enable extension -> on whitelisted only" in the _extension settings_ tab, and
* "Enable extension -> enabled" in the _site settings_ tab

You can also enable the extension on the extension settings page in the mean time:
![image](https://user-images.githubusercontent.com/12505802/181113538-9af5ccaa-ceb1-415d-af17-138170e00e1f.png)
... but I assume that you've decided that extension shouldn't run on every site by default for a reason.
