### ISSUE TITLE
Aspect ratio briefly resets during scene changes

### ISSUE THREAD

**Issue by lvctr** [tamius-han/ultrawidify#196]
**Describe the bug**
Ever since yesterday's update, every time there is a scene change on a video on YouTube the aspect ratio briefly resets to 16:9, then fixes itself after a split second.

**To Reproduce**
It happens in the following videos especially, every reload it happens at different parts of the video, but I can reliably reproduce the following timeframes.
https://www.youtube.com/watch?v=6JndkX_G5sI @ about 30 seconds.
https://www.youtube.com/watch?v=PuSBJ9Qblfg @ about 3 seconds, and about 6 seconds, but honestly the entire video.
It happens in every video when there's a scene change not just these.

**Expected behavior**
Like how it always has, don't briefly reset at scene changes.

**Screenshots**
Not applicable.

**Browser and OS**
 * Browser/browser version: Firefox 103.0
 * Operating system: Arch Linux (5.17.4)
 * Ultrawidify version: 5.1.2

**Additional info**
I've been watching these videos for months and it has always worked fine, it only started bugging out with yesterdays update.
Downgrading to 5.1.1 has fixed this issue for me.

Thanks in advance.

**Comment by tamius-han** [comment]
Think I figured out what's going on.

> _I haven't really, but I tried cherry-picking code from the UI redesign branch a bit harder and came up with something that seems to not reset shit on dark frames. Also #195, cos I'm not gonna copy this comment there._

Anyway, I think Firefox should get updates by the end of the weekend. I'll push it to AMO tomorrow, since it's a bit late now.

Edge and Chrome users: F (because review takes at least half a work week)
