### ISSUE TITLE
Not returning to 16:9

### ISSUE THREAD

**Issue by MrPractical** [tamius-han/ultrawidify#198]
Everything had been working fine until now, but starting today, while watching a YouTube video that switches between 16:9 and 21:9, like a movie review, when the video switches to 21:9, it will zoom in as it should, but when the video switches back to 16:9, it stays zoomed in, cutting off the top and bottom of the video. I've tried resetting and adjusting the settings, but nothing seems to fix it. And the videos I've tried aren't too dark at the top and bottom either. Thanks!

**Comment by Reezlaw** [comment]
I have the exact same issue. The extension forgets to zoom back out when the video returns to 16:9 after a 21:9 segment.

**Comment by tamius-han** [comment]
Thanks for the report.

Think I found the problem. Fixes will appear live when extension clears reviews of extension stores, and when your browser decides to update the extension (firefox: typically in less than a day; chrome: few days; edge: a week or so).
