### ISSUE TITLE
newbie question (anyone plz answer): How to automatically trigger Fit Width on page load?

### ISSUE THREAD

**Issue by drhouse** [tamius-han/ultrawidify#235]
maybe I'm missing something simple, and I tried all the options, but I can't figure out how to activate Fit Width crop whenever the page loads. I'm currently stuck having to manually press 'W' on every video... also, how can I deactivate Automatic Detection? it sometimes fights against my attempts to use Fit Width

**Comment by tamius-han** [comment]
> maybe I'm missing something simple, and I tried all the options, but I can't figure out how to activate Fit Width crop whenever the page loads.

This isn't currently possible, though there are plans to introduce this option (once I get some time to continue work on this addon). 

> also, how can I deactivate Automatic Detection? it sometimes fights against my attempts to use Fit Width

* Extension settings -> enable autodetection -> disable
* Site settings -> enable autodetection for [site] -> disable

**Comment by tamius-han** [comment]
In following days for Chrome, and "prolly somewhere by the end of the month" for Firefox, a feature that achieves this will be added to Ultrawidify.

![slika](https://github.com/tamius-han/ultrawidify/assets/12505802/d7827d3c-4cc8-445f-8138-83ac0f071e93)
