### ISSUE TITLE
Feature request: Make video settings available in full screen

### ISSUE THREAD

**Issue by MaluNoPeleke** [tamius-han/ultrawidify#244]
Can you add a button to the toolbar of a video player in full screen to easier select best video settings? I always forget all the different hot keys.

**Comment by tamius-han** [comment]
Yay Ultrawidify 6.0.0 — which brings user interface into the player — is currently in review on Chrome Web Store and Microsoft Edge Addons.

Firefox version probably comes by the end of the month.
