### ISSUE TITLE
Enable/disable keyboard shortcuts on 'video settings' doesn't work

### ISSUE THREAD

**Issue by tamius-han** [tamius-han/ultrawidify#65]
Note to future self:

* haven't looked at this issue at all
* the keyboard enable/disable section has been commented out in 'video settings' tab

* this can of worms is getting kicked way down the road, because it would be nice if buttons in 'vdeo settings' showed currently selected option

**Comment by i4y** [comment]
Keyboard shortcuts don't work. Only able to stretch image automatically on Netflix but unable to select crop factors or aspect ratio.

**Comment by xternal7** [comment]
That should have been a new issue, but okay.

Extension version, browser/OS, other extensions, did you just install the extension or have you used it for a while?
