### ISSUE TITLE
Unable to skip videos on youtube

### ISSUE THREAD

**Issue by helpvlc** [tamius-han/ultrawidify#89]
Sorry to let you know but i have found an issue with your plugin...........
TRUST ME.... I took forever going through all my extensions to figure out it was yours doing it.

my firefox version and i am on windows 10 something. but the firefox version i am using is 72.0.1 (64-bit). And the ultrawidify extension after i updated it has stuffed with my ability to fast forward on youtube with the right arrow key without the player stopping. Now i am still checking this out uninstalling plugins and reinstalling them disabling them etc but so far your extension is the only one when enabled at the addons area that the problem seems to happen too. I hope you can look into this please and if i am wrong and it isnt your plugin im sorry but the main plugins i am using is check to see if a twitch channel is live 
streamnotifier. tell me of new youtube videos with Youtube Subscription checker. 
ublock 
adblockplus 
ghostery
privacy badger
Cookie AutoDelete 3.0.2 
Browsec a vpn which isnt active
Full Screen Video For Youtube
Sticky Ducky Great for STOPPING videos from following you down the page except Twitch Still working on that when not logged it
Absolute Enable Right Click and Copy
Click to Enable Right-Click
No Script
grease monkey. Do you want all the scripts im using for youtube on there i have a few mostly about loading all the replies and showing more so you dont have to click on them.Only thing that does do something with the video is a space to play video but i have that turned off as i am yet to get the javascript to allow the spacebar in the addressbar as well as tell youtube to play with space i think thats an easy enough thing to do im lazy.
video download helper
umatrix
Youtube Watchmaker
I dont care about cookies
and a few script mining scripts No Coin NoMiner

I have checked with all of these on and off and only when your addon is on the video when you press the right button takes the video to the right by 5 seconds and pauses it. So you then have to click play and it does it again. Very annoying when you want to skip to a particular part of the video without stopping the video.

Anyway thank you for your time i appreciate it if you would check to see if its your addon or any suggestions as to what things in your addon i can turn off to avoid such a problem.

**Comment by helpvlc** [comment]
Yeah thats okay :-) Title was a little long.
Unable to use right arrow to skip through youtube videos while playing video is about it. 
I have gone back to the last version. 
But thank you, my title might not have been exact sorry about that.

**Comment by xternal7** [comment]
I am actually unable to reproduce this issue. Skipping left and right on youtube works just fine for me.

**Comment by helpvlc** [comment]
Weird could be other plugins but i wouldnt know, they all work fine,
with youtube together.

Using the version before this one works fine for me so i will use that.
Thank you for looking into it for me though.

AND THANKS FOR THE GREAT ADDON!!!!!!!

Its probably a combination of plugins including yours??????
But im good just being one behind because it worked flawlessly for me anyway :-)

Cheers
Great work on it BTW.
