### ISSUE TITLE
Can't whitelist primevideo.com

### ISSUE THREAD

**Issue by SunnyMoo** [tamius-han/ultrawidify#91]
**Describe the bug**
Using extension whitelist, can't enable for primevideo.com
Clicking "enable" has no effect.
Video settings remains grey.

**To Reproduce**
Set extension to whitelist mode, goto primevideo and try to enable for this site.

**Expected behavior**
Clicking enable should enable ultrawidify for primevideo and open access video settings section.

**Screenshots**
(don't mind the missing _www.primevideo.com_ i just forgot to switch tabs for this screenie see #90 )
![Annotation 2020-02-07 050449](https://user-images.githubusercontent.com/50081326/74000184-16b67b00-495f-11ea-8041-2c44627f0090.png)
![Annotation 2020-02-07 050403](https://user-images.githubusercontent.com/50081326/74000205-2930b480-495f-11ea-8ab0-fb28efb97ed3.png)

**Browser and OS**
 * Browser/browser version: Firefox 72 + Edge 79 (Edgium)
 * Operating system: Win10 Pro x64 1909
 * Ultrawidify version: 4.4.3.1

**Additional info**
Works flawlessly on Netflix
As a quick workaround maybe add a text whitelist in advanced settings ? I'd always like this option ;)
Thanks a lot !

**Comment by tamius-han** [comment]
> As a quick workaround maybe add a text whitelist in advanced settings ? I'd always like this option ;)

You actually can do that... sort of. In extension settings page (about:addons -> find ultrawidify -> preferences -> super advanced settings) you've got all extension settings in a form of a json object.

All the way to the bottom you should have some configs for certain sites. Find twitch and copy the block (ctrl+F for `www.twitch`), make sure every `{` is matched with a `}`. Maybe remove `type: "official"` line. Make sure to set `mode` and `autoar` lines to `3` (though they should already be set to 3 by default).

**Comment by SunnyMoo** [comment]
It works: primevideo is now whitelisted and I can change AR (tested on Lore S02E02).
Here's the block:
`    "www.primevideo.com": {
      "mode": 3,
      "autoar": 0,
      "override": true,
      "type": "official",
      "stretch": -1,
      "videoAlignment": -1,
      "keyboardShortcutsEnabled": 0,
      "DOM": {
        "player": {
          "manual": false,
          "querySelectors": "",
          "additionalCss": "",
          "useRelativeAncestor": false,
          "playerNodeCss": ""
        }
      },
      "cropModePersistence": -1
    }
  }`
Thank you 👍

**Comment by tamius-han** [comment]
Quick question. When you said:

> Clicking "enable" has no effect.
> Video settings remains grey.

Do you mean "video settings remains grey" or did you mean "video settings remains grey for up to 5 seconds"?

While both behaviours aren't very desirable, there's a bit of a difference between the two from my perspective (and I've only been able to observe the latter — although admittedly, I haven't tested on whitelisting sites on prime specifically).

**Comment by SunnyMoo** [comment]
"Video settings remains grey forever" ;)
May I add "enable button don't highlight" and "default button stay highlighted".
Fixed by modifying json in super advanced settings as you said 👍

**Comment by Shadoware** [comment]
Im using the lastest version(I already used the versions before current too). This addon doesn't work with primevideo all the time. Sometimes it works and sometimes dont and I have to restart the browser and try again.

Could you fix that Devs?

**Comment by tamius-han** [comment]
I don't have access to prime video, so this is gonna be a hard one.

Can you do me a favour and provide me a log?

Open popup, go to 'report a problem', click 'show logger' all the way at the bottom:

![Screenshot_20200212_094413](https://user-images.githubusercontent.com/12505802/74317810-51b01880-4d7c-11ea-9c8a-b80b8113e1fc.png)

If there's anything in Logger configuration panel, delete that and paste the following into the box:

```json
{ 
  "timeout": 15,
  "consoleOptions": {},
  "fileOptions": {
            "enabled": true,
            "debug": true,
            "init": true,
            "settings": true,
            "keyboard": true,
            "mousemove": false,
            "actionHandler": true,
            "comms": true,
            "playerDetect": true,
            "resizer": true,
            "scaler": true,
            "stretcher": true,
            "videoRescan": true,
            "playerRescan": true,
            "arDetect": true,
            "arDetect_verbose": true
          },
          "allowBlacklistedOrigins": {
            "periodicPlayerCheck": false
      }
   }
}
```
Click 'start logging', wait 15 seconds (you can hide the logger popup and try to change aspect ratio manually). When the logging is done, click 'export log', save the file and upload it to your comment.

[Non-TLDR](https://github.com/tamius-han/ultrawidify/wiki/How-to-provide-logs) version of "how to provide logs" instructions if above text is unclear.

Thanks.



Also: #87

**Comment by tamius-han** [comment]
If anyone else stumbles across this — I think I figured out why enabling sites manually didn't work and fixed it along the way. Fix will be out some time this/next week.

**Comment by SunnyMoo** [comment]
Thanks for the the update !

**Comment by tamius-han** [comment]
Fixed for Firefox.

Will be fixed for Chrome when Chrome Web Store decides to stop being a piece of shit store that requires 1+ month to review extensions.
