### ISSUE TITLE
Enabled extension breaks Google Voice layout

### ISSUE THREAD

**Issue by ayryq** [tamius-han/ultrawidify#92]
This is slightly weird one (I think):
Sometime in the last week Google Voice's online interface (voice.google.com) in Firefox 72.0.2 started showing me messages one character per line. I was able to correct the problem by disabling the UW extension. 
![Clipboard11](https://user-images.githubusercontent.com/4093149/74088717-54063000-4a67-11ea-972f-25e68d040ca8.png)
Setting UW to "never" within it's options, or setting it to ignore voice.google.com had no effect. Only disabling it from Firefox's addons page changed anything.

**Comment by tamius-han** [comment]
> Setting UW to "never" within it's options, or setting it to ignore voice.google.com had no effect. Only disabling it from Firefox's addons page changed anything.

Try reloading the page after setting it to ignore `voice.google.com` — does the issue still persist?

**Comment by ZackBoe** [comment]
Not sure if this is related, but seems like it's a good chance. I'm seeing some side effects on other sites as well. From what I could gather, the extension is globally injecting `uw.css` into all pages, and some rules are overriding the site's own styles. With the extension enabled, [npm's tabs & footer are forced into flex columns instead of rows.](https://streamable.com/a4oya)

**Comment by tamius-han** [comment]
Thanks for the pointer.

Now I only have to figure out how to "obfuscate" CSS class names ... so far, webpack plugins haven't proven very successful.

**Comment by tamius-han** [comment]
Okay, seems that Google Voice is US-only thing and I can't test it. Can someone please test a version for me?

* Download the version [Ultrawidify 2003.01.100 from here](https://stuff.lionsarch.tamius.net/ultrawidify/testing/) 
* Extract the zip file somewhere and load it as unpacked extension (instructions [here](https://github.com/tamius-han/ultrawidify/wiki/Nightly-and-testing-versions#installing-nightly-or-testing-version)

**Comment by ayryq** [comment]
The 2003.01.100 addon fixes this problem for me. See the screen capture: 
https://imgur.com/a/6IGZvQj

To answer the previous question directed at me, the issue still persists after reloading the page, restarting the browser, etc.

**Comment by tamius-han** [comment]
Fixed with 4.4.5, then.

Firefox users will be getting that update soon.
Chrome users are at the mercy of Chrome Store review.
