### ISSUE TITLE
autodetection not working on watch.tatasky.com

### ISSUE THREAD

**Issue by dineshdutta101** [tamius-han/ultrawidify#94]
**Describe the bug**
From past 3days auto video stretch not working on watch.tatasky.com while playing any channel. earlier it used to automatically stretch the video. but since few days i have to everytime manually press s or e to stretch the video everytime i play a new live channel

**To Reproduce**
please enable auto video stretch for watch.tatasky.com

**Screenshots**
![tatasky](https://user-images.githubusercontent.com/34351416/74404841-9f4a8500-4e51-11ea-94b7-073c45eda3a0.jpg)

**Browser and OS**
 * Browser/browser version:Chrome
 * Operating system:Windows 10
 * Ultrawidify version:Latest

**Additional info**
Any other things you want to say.

**Comment by tamius-han** [comment]
Does tatasky have any channels that do not require login?

Otherwise I can't reproduce this, as other sites don't appear to have this problem.

**Comment by tamius-han** [comment]
Possibly related to #91 

Closing cos #91 was resolved.
